### ISSUE TITLE
World Generation

### ISSUE THREAD

**Issue by Charismara** [ManasMods/reincarnated_mod#145]
# Biomes

- [x] #146
- [x] #147
- [x] #148

# Ores

- [x] #149

# Trees

- [x] #151
- [x] #154
- [ ] #434

# Structures

- [ ] #435
- [ ] #436
- [ ] #437
- [ ] #438
- [ ] #439
- [ ] #440
- [ ] #441
- [ ] #442
- [ ] #443
- [ ] #444
- [ ] #445

**Comment by Nieadni** [comment]
Trees: Sakura Trees (small and large, probably like 4 or so varieties), Palm Trees (again, like 4 varieties), and Ancient Trees (will just consist of oak logs, dark oak, birch, etc, just large versions of current trees)

Structures: oak human village, birch human village, spruce human village, jungle human village, desert human village, swamp human village, swamp lizardman village, oak goblin village, birch goblin village, sakura ogre village, charybdis cave, labyrinth entrance

**Comment by Nieadni** [comment]
Structures: 
Knight Camps
Thief Camps
Ruined Castles
Ruined Camps
Spider Nests
Moth Nests
Direwolf Camps
