### ISSUE TITLE
Helmet

### ISSUE THREAD

**Issue by Charismara** [ManasMods/reincarnated_mod#50]
- [ ] Silver
- [ ] Low Magisteel
- [ ] High Magisteel 
- [ ] Mithril
- [ ] Orichalcum
- [ ] Pure Magisteel
- [ ] Adamanite 
- [ ] Hihi'Irokane
- [ ] Hardened Leather
- [ ] Ant
- [ ] Knight
- [ ] Amoursaurus
- [ ] Charybdis Scale

**Comment by Nieadni** [comment]
Flint, Iron, Diamond and Netherite can be removed. The latter 3 are vanilla stuff and flint armour isnt a thing

**Comment by Charismara** [comment]
> Flint, Iron, Diamond and Netherite can be removed. The latter 3 are vanilla stuff and flint armour isnt a thing

Done
