### ISSUE TITLE
[Feature Request]: Smithing Bench Organisation Issue

### ISSUE THREAD

**Issue by Nieadni** [ManasMods/reincarnated_mod#538]
### Describe the new Feature as detailed as possible

![image](https://user-images.githubusercontent.com/103650147/200512294-3a9dece0-3f97-4877-b1c4-0c7aad624b0d.png)
Items are not ordered as they are added. This makes the inventory somewhat messy.

**Comment by Charismara** [comment]
# Issue 1
A comparator is proper sorting is required for Client **and** Server side. The Buttons only change the data slot index pointing to a registry entry which required both registry to be in the same order. This can only be ensured if we sort the registry with a custom comparator.
# Issue 2

**Comment by Nieadni** [comment]
I guess the only thing needed them for now is the Comparator to organise the Items

**Comment by Charismara** [comment]
yeah but we need sorting rules for the [SmithingBenchRecipe](https://github.com/ManasMods/reincarnated_mod/blob/master/src/main/java/com/github/manasmods/tensura/data/recipe/SmithingBenchRecipe.java) Comparator.

Right now the comparator just sorts them based on the result item id path:
```java
o1.getResultItem().getItem().getRegistryName().getPath().compareTo(o2.getResultItem().getItem().getRegistryName().getPath())
```

**Comment by Nieadni** [comment]
Well if the Comparator is set up, im fine with organising the items though I just want it to be sorted how it is registered in `TensuraRecipeProvider.java` in the `smithingRecipes` section

**Comment by Charismara** [comment]
i don't see a way to sort the recipes like they are written down in the data gen class. They look "random"

**Comment by Nieadni** [comment]
Bows, Leather, Bulldeer Leather, Gold, Silver, Iron, Ant, Serpent, Diamond, Knight Spider, Low Mag, Armoursauus, Armoursaurus Scalemail, High Mag, Charydis Scalemail, Mithril, Orichalcum, Pure Mag, Adamantite, Hihi, Anti-Magic Mask, Dark Set, Clown Masks

And where possible it goes Sword, Short Sword, Long Sword, Katana, Kodachi, Odachi, Pickaxe, Axe, Shovel, Hoe, Sickle, Helmet, Chestplate, Leggings, Boots.

Also sorry to ask this but after some thought, some may need to have 2 schematics unlocked before they show. For example a Silver Odachi would need 'Silver Gear Schematic' and then a 'Ogre Gear Techniques'

**Comment by Charismara** [comment]
the only thing i can do is:

1. sort recipes based on their 1. ingredient name (alphabetical)
2. sort recipes based on their 2. ingredient name (alphabetical, none = last)
3. sort recipes based on their 3. ingredient name (alphabetical, none = last)
4. sort recipes based on their 4. ingredient name (alphabetical, none = last)
5. sort recipes based on their 5. ingredient name (alphabetical, none = last)
6. Result name (alphabetical)

The next (higher) sorting level only happends when the current sorting value is equal. eg:
```
iron helmet (iron ingot, none)
iron sword (iron ingot, stick)

iron ingot == iron ingot
none < stick
```
or 
```
iron helmet (iron ingot, none)
gold helmet (gold ingot, none)

iron < gold 
```

**Comment by Nieadni** [comment]
I guess we would need a high sorting method but getting it to pair up to what I would like would be a pain it seems..

**Comment by Charismara** [comment]
i'm able to write the code if you're able to write a rule set (like i did as example in my last comment).

**Comment by Nieadni** [comment]
Is there absolutely no way where we can simply just list items?

**Comment by Nieadni** [comment]
I could easily get the main order down but it would be the `Sword, Short Sword, Long Sword, Katana, Kodachi, Odachi, Pickaxe, Axe, Shovel, Hoe, Sickle, Helmet, Chestplate, Leggings, Boots` part which trips me up

**Comment by Charismara** [comment]
> Is there absolutely no way where we can simply just list items?

No since others might add their recipes and items to our block

**Comment by Nieadni** [comment]
> 

Couldnt we also then have a part where we say 'If you add your own content, add the items where you deem fit. Currently they are organised based on their progression but also what makes the most sense.'

Then the organisation could look like 
`TensuraItems.SILVER_BOOTS, OtherModItems.CUSTOM_ITEM, Items.IRON_SWORD`

**Comment by Charismara** [comment]
sorting doesn't work like that in java

**Comment by Nieadni** [comment]
> sorting doesn't work like that in java

._. why must Java always be going against what I want.. I dont think even getting the correct order is going to be possible because all of the item amounts vary. Like just the armour alone wont be ordered correctly as if we go with most the least then itll be chestplate, leggings, helmet, boots..
![image](https://user-images.githubusercontent.com/103650147/201542198-35c0bab7-000a-4d10-87bd-de2ceba3f308.png)

**Comment by Nieadni** [comment]
Because my ideal order would be
`Normal Bows, Leather, Bulldeer Leather, Gold, Silver, Iron, Ant, Serpent, Diamond, Knight Spider, Low Mag, Armoursaurus, Armoursaurus Scalemail, High Mag, Charybdis Scalemail, Mithril, Orichalcum, Pure Mag, Adamantite, Hihi, Anti-Magic Mask, Dark Set, Clown Masks`

then

`Sword, Short Sword, Long Sword, Katana, Kodachi, Odachi, Pickaxe, Axe, Shovel, Hoe, Sickle, Helmet, Chestplate, Leggings, Boots`

**Comment by Charismara** [comment]
we can still check for class types of the result.

- result is `ArmorItem`
  - when true sort -> sort based on `ArmorMaterial.getDefenseForSlot(chestplate_slot)` -> sort alphabetical
  - when false sort -> sort after armor items and alphabetical

**Comment by Nieadni** [comment]
:o 

So then ofcourse you have the material list

`Normal Bows, Leather, Bulldeer Leather, Gold, Silver, Iron, Ant, Serpent, Diamond, Knight Spider, Low Mag, Armoursaurus, Armoursaurus Scalemail, High Mag, Charybdis Scalemail, Mithril, Orichalcum, Pure Mag, Adamantite, Hihi, Anti-Magic Mask, Dark Set, Clown Masks`

Bows = `SimpleShortBowItem, BowItem, SimpleLongBowItem, SimpleWarBowItem`

Everything else = `SimpleSwordItem, SimpleShortSwordItem, SimpleLongSwordItem, SimpleSpearItem, SimpleKunaiItem, SimplePickaxeItem, SimpleAxeItem, SimpleShovelItem, SimpleHoeItem, SimpleSickleItem, SimpleHelmetItem, SimpleChestplateItem, SimpleLeggingsItem, SimpleBootsItem`

**Comment by Charismara** [comment]
> * sort recipes based on their 1. ingredient name (alphabetical)
> * sort recipes based on their 2. ingredient name (alphabetical, none = last)
> * sort recipes based on their 3. ingredient name (alphabetical, none = last)
> * sort recipes based on their 4. ingredient name (alphabetical, none = last)
> * sort recipes based on their 5. ingredient name (alphabetical, none = last)
> * Result name (alphabetical)

Please provide a list of rules like I did in the example above

**Comment by Nieadni** [comment]
Ill try

- 1. Sort recipes on first ingredient of recipe `stick, leather, bulldeer leather, gold ingot, silver ingot, iron ingot, ant carapace, serpent scale, diamond, knight spider leg, knight spider carapace, low magisteel ingot, armoursaurus scale, high magisteel ingot, charybdis scale, mithril ingot, orichalcum ingot, pure magisteel ingot, adamantite ingot, hihi irokane ingot, clay ball, direwolf pelt`
- 2. Item Type - `SimpleShortBowItem, BowItem, SimpleLongBowItem, SimpleWarBowItem, SimpleSwordItem, SimpleShortSwordItem, SimpleLongSwordItem, SimpleSpearItem, SimpleKunaiItem, SimplePickaxeItem, SimpleAxeItem, SimpleShovelItem, SimpleHoeItem, SimpleSickleItem`
- 3. Armour Slot - `Head, Chest, Legs, Feet`

**Comment by Charismara** [comment]
okay i don't get that. lol

Try to create a rule map like this: https://atlas.mindmup.com/2022/11/c5f8190063fd11edbe3f01c71abde0f9/recipe_sorting/index.html
