### ISSUE TITLE
[Feature Request]: Weapon Templates

### ISSUE THREAD

**Issue by Nieadni** [ManasMods/reincarnated_mod#552]
### Describe the new Feature as detailed as possible

I wasn't sure what to name this issue however it is for when registering items in `src/main/java/com/github/manasmods/tensura/registry/ItemRegistry.java`

We are in need of the following templates. In the same formatting as the `SimpleSwordItem`

- [x] #620
1.5 Block Range, 2 Attack Speed

- [x] SimpleLongSwordItem
3.5 Block Range, 1.2 Attack Speed, Permanent Sweeping Edge II Effect (not actual enchantment)

- [x] SimpleGreatSwordItem
5 Block Range, 0.8 Attack Speed, Permanent Sweeping Edge III Effect (not actual enchantment)

- [ ] SimpleKunaiItem
An item which you throw. It could travel 15 blocks before drop off (same as regular bow). 5 or 10 tick recharge time?

- [x] SimpleSpearItem
3x the distance of a regular sword, 0.7x the speed?

- [ ] SimpleShortBowItem
Total of 4 damage when max charge with a 10 tick charge time. Durability of 231. Distance of 10 blocks before drop-off.

- [ ] SimpleLongBowItem
Total of 8 damage when max charge with a 30 tick charge time. Durability of 500. Distance of 30 blocks before drop-off.

- [ ] SimpleWarBowItem
Total of 16 damage when max charge with a 60 tick charge time. Durability of 615. Distance of 60 blocks before drop-off.

I also request that `SimpleSickleItem` be changed to be in the same formatting as `SimpleHoeItem`

Note: A regular bow has a Actual Damage of 6, 20 Tick Recharge Time, Distance of 15 Blocks and 384 Durability.

**Comment by Charismara** [comment]
a description about the "weapon abilities" would be nice

**Comment by Nieadni** [comment]
Updated^^

**Comment by Nieadni** [comment]
Added `top priority` label
