### ISSUE TITLE
[Feature Request]: NPC's

### ISSUE THREAD

**Issue by Nieadni** [ManasMods/reincarnated_mod#557]
### Describe the new Feature as detailed as possible

` Goals `

TBA

` Notes `

¬ Vanilla Villages will be turned to false for default (gamerule to toggle them back on when creating a world, something like `/gamerule doVillageSpawn on` or something if it doesnt already exist.)
¬ NPC will have height and stats of the player races.
¬ All NPC's will be neutral, to a certain extent. Once the player deals 2 hearts of damage, the NPC will then attack.
¬ In neutral state, the following will all just have nothing in their hands, but when going to attack something, will have the following in their hand;

          - Human Weaponsmith : Iron Sword
          - Ogre Weaponsmith : Iron Katana
          - Dwarf Weaponsmith : Silver Sword
          - Human Toolsmith : Iron Shovel
          - Ogre Toolsmith : Iron Axe
          - Dwarf Toolsmith : Iron Pickaxe
          - Human Butcher : Iron Short Sword
          - Elf Butcher : Gold Short Sword
          - Ogre Butcher : Iron Short Sword
          - Dwarf Butcher : Silver Short Sword

Every other NPC will just have their hands.

` Mobs `

**31 New Villagers**

¬ Free Guild Clerk
¬ Human Magic Trainer
¬ Ogre Magic Trainer
¬ Human Battlewill Trainer
¬ Ogre Battlewill Trainer
¬ Human Armourer
¬ Ogre Armourer
¬ Dwarf Armourer
¬ Human Weaponsmith
¬ Ogre Weaponsmith
¬ Dwarf Weaponsmith
¬ Human Toolsmith
¬ Ogre Toolsmith
¬ Dwarf Toolsmith
¬ Human Butcher
¬ Elf Butcher
¬ Ogre Butcher
¬ Dwarf Butcher
¬ Human Farmer
¬ Ogre Farmer
¬ Human Fisherman
¬ Elf Fisherman
¬ Ogre Fisherman
¬ Dwarf Fisherman
¬ Human Clothier
¬ Ogre Clothier
¬ Dwarf Clothier
¬ Human Chef
¬ Elf Chef
¬ Ogre Chef
¬ Dwarf Chef

`Items`

¬ Barrier Tome
¬ Earth Tome
¬ Explosion Tome
¬ Fire Tome
¬ Gravity Tome
¬ Ice Tome
¬ Illusion Tome
¬ Lightning Tome
¬ Recovery Tome
¬ Space Tome
¬ Water Tome
¬ Wind Tome

¬ Aura Shield Manual
¬ Aura Sword Manual
¬ Battlewill Manual
¬ Diamond Path Manual
¬ Formhide Manual
¬ Instant Move Manual
¬ Magic Bullet Manual
¬ Ogre-Flame Manual
¬ Ogre-Sword Cannon Manual
¬ Ogre Sword Guillotine Manual

¬ Direwolf Fur Clothing Set
¬ Dwarf Clothing Set 1
¬ Dwarf Clothing Set 2
¬ Dwarf Clothing Set 3
¬ Human Clothing Set 1
¬ Human Clothing Set 2
¬ Human Clothing Set 3
¬ Ogre Clothing Set 1
¬ Ogre Clothing Set 2
¬ Ogre Clothing Set 3
¬ Paladin Clothing Set

Further Notes:

¬ Use the base steve skin as the texture for the mobs though will need some thing in a section of code or something to say if the model should be slim or wide (alex or steve style). I can provide a .zip file though there is a chance that it may be missing some of the temp textures. Fill these in if I have missed them please!

[TR Skins.zip](https://github.com/ManasMods/reincarnated_mod/files/10096975/TR.Skins.zip)

**Comment by Charismara** [comment]
> ¬ Vanilla Villages will be turned to false for default (gamerule to toggle them back on when creating a world, something like `/gamerule doVillageSpawn on` or something if it doesnt already exist.)

A Config option would be better then a game rule tbh


> 31 New Villagers

Please create sub issues with clear descriptions

> Items

Those things probably should be a separate issue too

**Comment by Nieadni** [comment]
> A Config option would be better then a game rule tbh

Wouldnt a gamerule be better? Its easier to change a gamerule on world creation. Though I dont know how configs work and how user-friendly they are.

> Please create sub issues with clear descriptions

._. It would legit just be most the same. Atleast for the beginning. It would only be the trades where id need seperate issues and for that, we have the excel sheet where things are the most up-to-date

> Items

I added these in as I just made 1 big list on discord. 

I could make a milestone and add the 40 or so needed issues but chances are I could miss something

**Comment by Charismara** [comment]
> ._. It would legit just be most the same. Atleast for the beginning. It would only be the trades where id need seperate issues and for that, we have the excel sheet where things are the most up-to-date

&

> I added these in as I just made 1 big list on discord.
> 
> I could make a milestone and add the 40 or so needed issues but chances are I could miss something

It's easier for us (Devs) to work on issues with all information in it and we would be able to track progress on those things

**Comment by Charismara** [comment]
can this issue be closed?
