### ISSUE TITLE
[Feature Request]: Vulnerability during Race Selection

### ISSUE THREAD

**Issue by Nieadni** [ManasMods/reincarnated_mod#594]
### Describe the new Feature as detailed as possible

Im not sure what would be best to fix this though maybe something like Invisibility and Max Regen when in the Race Selector (without particles) or possibly making some dimension where the player is sent to while they are choosing a race or if we are somehow able to interrupt them spawning in the first place? Iirc you cant take damage when in the End Credits (after killing Ender Dragon) so we could maybe do whatever that does? Including the dirt background behind the GUI?

**Comment by Charismara** [comment]
we just gonna set the player invulnerable before the menu is opened and set him vulnerable again when the menu is about to be closed
