### ISSUE TITLE
[Feature Request]: Weapons, Schematics, and the Smithing Bench

### ISSUE THREAD

**Issue by Nieadni** [ManasMods/reincarnated_mod#614]
### Describe the new Feature as detailed as possible

Add 'Great Sword' Variants for all materials which have the Short Sword and Sword
Add 'Tachi' Variants for all materials which have the Short Sword and Sword

Recipes:
Short Sword + Kodachi = 1 Ingot + 1 Stick
Sword + Katana = 2 Ingots + 1 Stick
Long Sword + Tachi = 3 Ingots + 1 Stick
Great Sword + Odachi = 4 Ingots + 2 Stick

Multiple Schematics for Item (Minh said it was possible)

Long Swords will need the material schematic + 'Long Swords Schematic'
Tachis will need the material schematic + 'Long Swords Schematic' + 'Japanese-Style Swords Schematic'
etc

----

So all the new items will be:

- Wooden Great Sword
- Wooden Tachi
- Flint Great Sword
- Flint Tachi
- Stone Great Sword
- Stone Tachi
- Golden Great Sword
- Golden Tachi
- Silver Great Sword
- Silver Tachi
- Iron Great Sword
- Iron Tachi
- Diamond Great Sword
- Diamond Tachi
- Low Magisteel Great Sword
- Low Magisteel Tachi
- High Magisteel Great Sword
- High Magisteel Tachi
- Mithril Great Sword
- Mithril Tachi
- Orichalcum Great Sword
- Orichalcum Tachi
- Pure Magisteel Great Sword
- Pure Magisteel Tachi
- Adamantite Great Sword
- Adamantite Tachi
- Hihi'Irokane Great Sword
- Hihi'Irokane Tachi

- Long Swords Schematic
- Great Swords Schematic
- Japanese-Style Swords Schematic

We will also need a weapon builder for Great Swords. Ill update #552

**Comment by Charismara** [comment]
this needs

- [ ] #552
