### ISSUE TITLE
[Feature Request]: Bows

### ISSUE THREAD

**Issue by Nieadni** [ManasMods/reincarnated_mod#615]
### Describe the new Feature as detailed as possible

The format will be
Name / Damage Multiplier / Speed (Draw Speed Till Max, in Ticks) / Durability

| Name                   | Damage Multiplier             | Draw Speed (Ticks)            | Durability |
| :------------------: | :------------------: |:------------------: |:------------------: |
| Short Bow              | 2                             | 14                            | 231 |
| Long Bow               | 6                             | 28                            | 500 |
| War Bow                | 14                            | 40                            | 615 |
| Spider Short Bow       | 6                             | 10                            | 578 |
| Spider Bow             | 8                             | 16                            | 980 |
| Spider Long Bow        | 10                            | 24                            | 1250 |
| Spider War Bow         | 18                            | 34                            | 1538 |

For textures, just use the temp texture and rename it

**Comment by Charismara** [comment]
can u do a table for better readability? (GitHub uses `Markdown` which can do tables)

**Comment by Nieadni** [comment]
There. Is that better?
